[colors.primary]
background: '0x162023'
foreground: '0xd2eff0'

# Normal colors
[colors.normal]
   black:   '0x14282c'
   yellow:  '0x0db383'
   red:     '0xE83f35'
   green:   '0x34bb56'
   blue:    '0x0c425c'
   magenta: '0xd150d1'
   cyan:    '0x60aed3'
   white:   '0xbceff0'    

# Bright colors
[colors.bright]
   black:   '0x1b863c'
   red:     '0xd95afa'
   green:   '0x455a8f'
   yellow:  '0x1b363c'
   blue:    '0x295059'
   magenta: '0x306672'
   cyan:    '0x66a7b6'
   white:   '0xa6eff2'
#   dim:
#   black:   '0xd2eff0'
#   red:     '0x7c212d'
#   green:   '0x6fcfa2'
#   yellow:  '0x61A276'
#   blue:    '0x2b5c66'
#   magenta: '0xaf40ad'
#   cyan:    '0x13a8ce'
#   white:   '0x3d577f'
  
